Config = Config or {}

Config.UsingPsHousing = false
Config.UsingDefaultQBApartments = true
Config.OnlyShowOnDuty = true
Config.UseCQCMugshot = true

-- Front, Back Side. Use 4 for both sides, we recommend leaving at 1 for default.
Config.MugPhotos = 1

-- If set to true = Fine gets automatically removed from bank automatically charging the player.
-- If set to false = The fine gets sent as an Invoice to their phone and it us to the player to pay for it, can remain unpaid and ignored.
Config.BillVariation = true

-- If set to false (default) = The fine amount is just being removed from the player's bank account
-- If set to true = The fine amount is beeing added to the society account after being removed from the player's bank account
Config.QBBankingUse = false

-- Set up your inventory to automatically retrieve images when a weapon is registered at a weapon shop or self-registered.
-- If you're utilizing lj-inventory's latest version from GitHub, no further modifications are necessary. 
-- However, if you're using a different inventory system, please refer to the "Inventory Edit | Automatic Add Weapons with images" section in ps-mdt's README.
Config.InventoryForWeaponsImages = "ox_inventory"

-- "LegacyFuel", "lj-fuel", "ps-fuel"
Config.Fuel = "ox_fuel"

-- Google Docs Link
Config.sopLink = {
    ['police'] = '',
    ['ambulance'] = '',
    ['bcso'] = '',
    ['doj'] = '',
    ['sast'] = '',
    ['sasp'] = '',
    ['doc'] = '',
    ['lssd'] = '',
    ['sapr'] = '',
}

-- Google Docs Link
Config.RosterLink = {
    ['police'] = '',
    ['ambulance'] = '',
    ['bcso'] = '',
    ['doj'] = '',
    ['sast'] = '',
    ['sasp'] = '',
    ['doc'] = '',
    ['lssd'] = '',
    ['sapr'] = '',	
}

Config.PoliceJobs = {
    ['police'] = true,
    ['lspd'] = false,
    ['bcso'] = false,
    ['sast'] = false,
    ['sasp'] = false,
    ['doc'] = false,
    ['lssd'] = false,
    ['sapr'] = false,
    ['pa'] = false
}

Config.AmbulanceJobs = {
    ['ambulance'] = true,
    ['doctor'] = false
}

Config.DojJobs = {
    ['lawyer'] = true,
    ['judge'] = false
}

-- This is a workaround solution because the qb-menu present in qb-policejob fills in an impound location and sends it to the event. 
-- If the impound locations are modified in qb-policejob, the changes must also be implemented here to ensure consistency.

Config.ImpoundLocations = {
    [1] = vector4(436.68, -1007.42, 27.32, 180.0),
    [2] = vector4(-436.14, 5982.63, 31.34, 136.0),
}

-- Support for Wraith ARS 2X. 

Config.UseWolfknightRadar = false
Config.WolfknightNotifyTime = 5000 -- How long the notification displays for in milliseconds (30000 = 30 seconds)
Config.PlateScanForDriversLicense = false -- If true, plate scanner will check if the owner of the scanned vehicle has a drivers license

-- IMPORTANT: To avoid making excessive database queries, modify this config to true 'CONFIG.use_sonorancad = true' setting in the configuration file located at 'wk_wars2x/config.lua'. 
-- Enabling this setting will limit plate checks to only those vehicles that have been used by a player.

Config.LogPerms = {
	['ambulance'] = {
		[4] = true,
	},
	['police'] = {
		[4] = true,
	},
    ['bcso'] = {
		[4] = false,
	},
    ['sast'] = {
		[4] = false,
	},
    ['sasp'] = {
		[4] = false,
	},
    ['sapr'] = {
		[4] = false,
	},
    ['doc'] = {
		[4] = false,
	},
    ['lssd'] = {
		[4] = false,
	},
}

Config.RemoveIncidentPerms = {
	['ambulance'] = {
		[4] = true,
	},
	['police'] = {
		[4] = true,
	},
    ['bcso'] = {
		[4] = false,
	},
    ['sast'] = {
		[4] = false,
	},
    ['sasp'] = {
		[4] = false,
	},
    ['sapr'] = {
		[4] = false,
	},
    ['doc'] = {
		[4] = false,
	},
    ['lssd'] = {
		[4] = false,
	},
}

Config.RemoveReportPerms = {
	['ambulance'] = {
		[4] = true,
	},
	['police'] = {
		[4] = true,
	},
    ['bcso'] = {
		[4] = false,
	},
    ['sast'] = {
		[4] = false,
	},
    ['sasp'] = {
		[4] = false,
	},
    ['sapr'] = {
		[4] = false,
	},
    ['doc'] = {
		[4] = false,
	},
    ['lssd'] = {
		[4] = false,
	},
}

Config.RemoveWeaponsPerms = {
	['ambulance'] = {
		[4] = true,
	},
	['police'] = {
		[4] = true,
	},
    ['bcso'] = {
		[4] = false,
	},
    ['sast'] = {
		[4] = false,
	},
    ['sasp'] = {
		[4] = false,
	},
    ['sapr'] = {
		[4] = false,
	},
    ['doc'] = {
		[4] = false,
	},
    ['lssd'] = {
		[4] = false,
	},
}

Config.PenalCodeTitles = {
    [1] = 'FORBRYDELSER MOD PERSONER',
    [2] = 'FORBRYDELSER INVOLVERENDE TYVERI',
    [3] = 'FORBRYDELSER INVOLVERENDE BEDRAGERI',
    [4] = 'FORBRYDELSER INVOLVERENDE SKADE PÅ EJENDOM',
    [5] = 'FORBRYDELSER MOD OFFENTLIG ADMINISTRATION',
    [6] = 'FORBRYDELSER MOD OFFENTLIG ORDEN',
    [7] = 'FORBRYDELSER MOD SUNDHED OG MORALER',
    [8] = 'FORBRYDELSER MOD OFFENTLIG SIKKERHED',
    [9] = 'FORBRYDELSER INVOLVERENDE DRIFT AF ET KØRETØJ',
    [10] = 'FORBRYDELSER INVOLVERENDE DYRS VELBEFINDEN',
}


Config.PenalCode = {
    [1] = {
        [1] = {title = 'Simpelt Angreb', class = 'Forbrydelse', id = 'K.K. 1001', months = 7, fine = 500, color = 'grøn', description = 'Når en person bevidst eller med vilje forårsager fysisk kontakt med en anden (uden våben)'},
        [2] = {title = 'Angreb', class = 'Forbrydelse', id = 'K.K. 1002', months = 15, fine = 850, color = 'orange', description = 'Hvis en person bevidst eller med vilje forårsager skade på en anden (uden våben)'},
        [3] = {title = 'Forværret Angreb', class = 'Forbrydelse', id = 'K.K. 1003', months = 20, fine = 1250, color = 'orange', description = 'Når en person utilsigtet og uansvarligt forårsager legemsskade på en anden som følge af en konfrontation OG forårsager legemsskade'},
        [4] = {title = 'Angreb med Dødeligt Våben', class = 'Forbrydelse', id = 'K.K. 1004', months = 30, fine = 3750, color = 'rød', description = 'Når en person bevidst, med vilje eller uansvarligt forårsager legemsskade på en anden person OG enten forårsager alvorlig legemsskade eller bruger eller viser et dødeligt våben'},
        [5] = {title = 'Uagtsomt Manddrab', class = 'Forbrydelse', id = 'K.K. 1005', months = 60, fine = 7500, color = 'rød', description = 'Når en person utilsigtet og uansvarligt forårsager en andens død'},
        [6] = {title = 'Køretøjsmanddrab', class = 'Forbrydelse', id = 'K.K. 1006', months = 75, fine = 7500, color = 'rød', description = 'Når en person utilsigtet og uansvarligt forårsager en andens død med et køretøj'},
        [7] = {title = 'Forsøg på Mord på en Civil', class = 'Forbrydelse', id = 'K.K. 1007', months = 50, fine = 7500, color = 'rød', description = 'Når en ikke-regeringsperson bevidst angriber en anden med hensigt at dræbe'},
        [8] = {title = 'Anden Grad Mord', class = 'Forbrydelse', id = 'K.K. 1008', months = 100, fine = 15000, color = 'rød', description = 'Enhver forsætlig drab, der ikke er forudgående overvejet eller planlagt. En situation, hvor morderen kun har til hensigt at påføre alvorlig legemsskade.'},
        [9] = {title = 'Medvirkende til Anden Grad Mord', class = 'Forbrydelse', id = 'K.K. 1009', months = 50, fine = 5000, color = 'rød', description = 'At være til stede og/eller deltage i handlingen som medvirkende'},
        [10] = {title = 'Første Grad Mord', class = 'Forbrydelse', id = 'K.K. 1010', months = 0, fine = 0, color = 'rød', description = 'Enhver forsætlig drab, der er villet og forudgående overvejet med ondskab.'},
        [11] = {title = 'Medvirkende til Første Grad Mord', class = 'Forbrydelse', id = 'K.K. 1011', months = 0, fine = 0, color = 'rød', description = 'At være til stede og/eller deltage i handlingen som medvirkende'},
        [12] = {title = 'Mord på en Offentlig Tjenestemand eller Fredsofficer', class = 'Forbrydelse', id = 'K.K. 1012', months = 0, fine = 0, color = 'rød', description = 'Enhver forsætlig drab, der udføres på en regeringsansat'},
        [13] = {title = 'Forsøg på Mord på en Offentlig Tjenestemand eller Fredsofficer', class = 'Forbrydelse', id = 'K.K. 1013', months = 65, fine = 10000, color = 'rød', description = 'Enhver angreb, der udføres på en regeringsansat med hensigten at forårsage død'},
        [14] = {title = 'Medvirkende til Mord på en Offentlig Tjenestemand eller Fredsofficer', class = 'Forbrydelse', id = 'K.K. 1014', months = 0, fine = 0, color = 'rød', description = 'At være til stede og/eller deltage i handlingen som medvirkende'},
        [15] = {title = 'Ulovlig Frihedsberøvelse', class = 'Forbrydelse', id = 'K.K. 1015', months = 10, fine = 600, color = 'grøn', description = 'Handlingen med at tage en anden mod deres vilje og holde dem i en længere periode'},
        [16] = {title = 'Kidnapning', class = 'Forbrydelse', id = 'K.K. 1016', months = 15, fine = 900, color = 'orange', description = 'Handlingen med at tage en anden mod deres vilje i en kort periode'},
        [17] = {title = 'Medvirkende til Kidnapning', class = 'Forbrydelse', id = 'K.K. 1017', months = 7, fine = 450, color = 'orange', description = 'At være til stede og/eller deltage i handlingen som medvirkende'},
        [18] = {title = 'Forsøg på Kidnapning', class = 'Forbrydelse', id = 'K.K. 1018', months = 10, fine = 450, color = 'orange', description = 'Handlingen med at forsøge at tage nogen mod deres vilje'},
        [19] = {title = 'Gidseltagning', class = 'Forbrydelse', id = 'K.K. 1019', months = 20, fine = 1200, color = 'orange', description = 'Handlingen med at tage en anden mod deres vilje med henblik på personlig gevinst'},
        [20] = {title = 'Medvirkende til Gidseltagning', class = 'Forbrydelse', id = 'K.K. 1020', months = 10, fine = 600, color = 'orange', description = 'At være til stede og/eller deltage i handlingen som medvirkende'},
        [21] = {title = 'Ulovlig Frihedsberøvelse af en Offentlig Tjenestemand eller Fredsofficer.', class = 'Forbrydelse', id = 'K.K. 1021', months = 25, fine = 4000, color = 'orange', description = 'Handlingen med at tage en regeringsansat mod deres vilje i en længere periode'},
        [22] = {title = 'Kriminelle Trusler', class = 'Forbrydelse', id = 'K.K. 1022', months = 5, fine = 500, color = 'orange', description = 'Handlingen med at erklære hensigten om at begå en forbrydelse mod en anden'},
        [23] = {title = 'Risikabelt Udsættelse for Fare', class = 'Forbrydelse', id = 'K.K. 1023', months = 10, fine = 1000, color = 'orange', description = 'Handlingen med at ignorere en andens sikkerhed, hvilket kan sætte en anden i fare for død eller legemsskade'},
        [24] = {title = 'Banderelateret Skyderi', class = 'Forbrydelse', id = 'K.K. 1024', months = 30, fine = 2500, color = 'rød', description = 'Handlingen, hvor et skydevåben affyres i forbindelse med bandevirksomhed'},
        [25] = {title = 'Kannibalisme', class = 'Forbrydelse', id = 'K.K. 1025', months = 0, fine = 0, color = 'rød', description = 'Handlingen, hvor en person frivilligt indtager en andens kød'},
        [26] = {title = 'Tortur', class = 'Forbrydelse', id = 'K.K. 1026', months = 40, fine = 4500, color = 'rød', description = 'Handlingen med at forvolde skade på en anden for at udtrække information og/eller for egen fornøjelse'},
    },
    [2] = {
        [1] = {title = 'Petty Theft', class = 'Overtrædelse', id = 'K.K. 2001', months = 0, fine = 250, color = 'grøn', description = 'Tyveri af ejendom under $50 i værdi'},
        [2] = {title = 'Grand Theft', class = 'Forbrydelse', id = 'K.K. 2002', months = 10, fine = 600, color = 'grøn', description = 'Tyveri af ejendom over $700 i værdi'},
        [3] = {title = 'Grand Theft Auto A', class = 'Forbrydelse', id = 'K.K. 2003', months = 15, fine = 900, color = 'grøn', description = 'Handlingen med at stjæle et køretøj, der tilhører en anden, uden tilladelse'},
        [4] = {title = 'Grand Theft Auto B', class = 'Forbrydelse', id = 'K.K. 2004', months = 35, fine = 3500, color = 'grøn', description = 'Handlingen med at stjæle et køretøj, der tilhører en anden, uden tilladelse, mens man er bevæbnet'},
        [5] = {title = 'Bilrøveri', class = 'Forbrydelse', id = 'K.K. 2005', months = 30, fine = 2000, color = 'orange', description = 'Handlingen med at tage et køretøj fra dets besætningsmedlemmer ved magt'},
        [6] = {title = 'Indbrud', class = 'Forbrydelse', id = 'K.K. 2006', months = 10, fine = 500, color = 'grøn', description = 'Handlingen med at trænge ulovligt ind i en bygning med forsæt om at begå en forbrydelse, især tyveri.'},
        [7] = {title = 'Røveri', class = 'Forbrydelse', id = 'K.K. 2007', months = 25, fine = 2000, color = 'grøn', description = 'Handlingen med at tage ejendom ulovligt fra en person eller sted ved magt eller trussel om magt.'},
        [8] = {title = 'Medvirkende til Røveri', class = 'Forbrydelse', id = 'K.K. 2008', months = 12, fine = 1000, color = 'grøn', description = 'At være til stede og/eller deltage i handlingen som medvirkende'},
        [9] = {title = 'Forsøg på Røveri', class = 'Forbrydelse', id = 'K.K. 2009', months = 20, fine = 1000, color = 'grøn', description = 'Handlingen med at forsøge at tage ejendom ulovligt fra en person eller sted ved magt eller trussel om magt.'},
        [10] = {title = 'Bevæbnet Røveri', class = 'Forbrydelse', id = 'K.K. 2010', months = 30, fine = 3000, color = 'orange', description = 'Handlingen med at tage ejendom ulovligt fra en person eller sted ved magt eller trussel om magt, mens man er bevæbnet.'},
        [11] = {title = 'Medvirkende til Bevæbnet Røveri', class = 'Forbrydelse', id = 'K.K. 2011', months = 15, fine = 1500, color = 'orange', description = 'At være til stede og/eller deltage i handlingen som medvirkende'},
        [12] = {title = 'Forsøg på Bevæbnet Røveri', class = 'Forbrydelse', id = 'K.K. 2012', months = 25, fine = 1500, color = 'orange', description = 'Handlingen med at forsøge at tage ejendom ulovligt fra en person eller sted ved magt eller trussel om magt, mens man er bevæbnet.'},
        [13] = {title = 'Stor Tyveri', class = 'Forbrydelse', id = 'K.K. 2013', months = 45, fine = 7500, color = 'orange', description = 'Tyveri af personlig ejendom med en værdi over et lovligt specificeret beløb.'},
        [14] = {title = 'Forlade uden at Betale', class = 'Overtrædelse', id = 'K.K. 2014', months = 0, fine = 500, color = 'grøn', description = 'Handlingen med at forlade et etablissement uden at betale for leveret service'},
        [15] = {title = 'Besiddelse af Ikke-Lovlig Valuta', class = 'Forbrydelse', id = 'K.K. 2015', months = 10, fine = 750, color = 'grøn', description = 'At være i besiddelse af stjålet valuta'},
        [16] = {title = 'Besiddelse af Regjeringsudstedte Genstande', class = 'Forbrydelse', id = 'K.K. 2016', months = 15, fine = 1000, color = 'grøn', description = 'At være i besiddelse af genstande, der kun kan erhverves af regeringsansatte'},
        [17] = {title = 'Besiddelse af Genstande Brugt ved Begåelse af en Forbrydelse', class = 'Forbrydelse', id = 'K.K. 2017', months = 10, fine = 500, color = 'grøn', description = 'At være i besiddelse af genstande, der tidligere blev brugt til at begå forbrydelser'},
        [18] = {title = 'Salg af Genstande Brugt ved Begåelse af en Forbrydelse', class = 'Forbrydelse', id = 'K.K. 2018', months = 15, fine = 1000, color = 'orange', description = 'Handlingen med at sælge genstande, der tidligere blev brugt til at begå forbrydelser'},
        [19] = {title = 'Tyveri af et Fly', class = 'Forbrydelse', id = 'K.K. 2019', months = 20, fine = 1000, color = 'grøn', description = 'Handlingen med at stjæle et fly'},
    },
    [3] = {
        [1] = {title = 'For at udgive sig for', class = 'Forbrydelse', id = 'K.K. 3001', months = 15, fine = 1250, color = 'grøn', description = 'Handlingen med falsk at identificere sig som en anden person for at bedrage'},
        [2] = {title = 'For at udgive sig for en Fredsofficer eller Offentlig Tjenestemand', class = 'Forbrydelse', id = 'K.K. 3002', months = 25, fine = 2750, color = 'grøn', description = 'Handlingen med falsk at identificere sig som en regeringsansat for at bedrage'},
        [3] = {title = 'For at udgive sig for en Dommer', class = 'Forbrydelse', id = 'K.K. 3003', months = 0, fine = 0, color = 'grøn', description = 'Handlingen med falsk at identificere sig som en dommer for at bedrage'},
        [4] = {title = 'Besiddelse af Stjålet Identifikation', class = 'Forbrydelse', id = 'K.K. 3004', months = 10, fine = 750, color = 'grøn', description = 'At have en andens identifikation uden samtykke'},
        [5] = {title = 'Besiddelse af Stjålet Regjeringsidentifikation', class = 'Forbrydelse', id = 'K.K. 3005', months = 20, fine = 2000, color = 'grøn', description = 'At have identifikationen af en regeringsansat uden samtykke'},
        [6] = {title = 'Afpresning', class = 'Forbrydelse', id = 'K.K. 3006', months = 20, fine = 900, color = 'orange', description = 'At true eller forvolde skade på en person eller ejendom for økonomisk gevinst'},
        [7] = {title = 'Bedrageri', class = 'Forbrydelse', id = 'K.K. 3007', months = 10, fine = 450, color = 'grøn', description = 'At bedrage en anden for økonomisk gevinst'},
        [8] = {title = 'Falsk', class = 'Forbrydelse', id = 'K.K. 3008', months = 15, fine = 750, color = 'grøn', description = 'At forfalske juridisk dokumentation for personlig gevinst'},
        [9] = {title = 'Hvidvask af penge', class = 'Forbrydelse', id = 'K.K. 3009', months = 0, fine = 0, color = 'rød', description = 'Behandlingen af stjålne penge til lovlig valuta'},
    },
    [4] = {
        [1] = {title = 'Hærværk', class = 'Forbrydelse', id = 'K.K. 4001', months = 10, fine = 450, color = 'grøn', description = 'For en person at befinde sig inden for grænserne af et sted, hvor de ikke har lovligt adgang'},
        [2] = {title = 'Alvorligt Hærværk', class = 'Forbrydelse', id = 'K.K. 4002', months = 15, fine = 1500, color = 'grøn', description = 'For en person gentagne gange at være trængt ind i grænserne af et sted, hvor de bevidst ikke har lovligt adgang'},
        [3] = {title = 'Brandstiftelse', class = 'Forbrydelse', id = 'K.K. 4003', months = 15, fine = 1500, color = 'orange', description = 'Brugen af ​​ild og brændstoffer til vilje og ondsindet at ødelægge, skade eller forårsage død på en person eller ejendom'},
        [4] = {title = 'Hærværk', class = 'Overtrædelse', id = 'K.K. 4004', months = 0, fine = 300, color = 'grøn', description = 'Vilfuld ødelæggelse af ejendom'},
        [5] = {title = 'Hærværk af Regjerings Ejendom', class = 'Forbrydelse', id = 'K.K. 4005', months = 20, fine = 1500, color = 'grøn', description = 'Vilfuld ødelæggelse af regeringens ejendom'},
        [6] = {title = 'Affaldsspredning', class = 'Overtrædelse', id = 'K.K. 4006', months = 0, fine = 200, color = 'grøn', description = 'Vilfuld bortskaffelse af affald i åbne områder og ikke i anviste containere'},
    },
    [5] = {
        [1] = {title = 'Bestikkelse af en Regeringsansat', class = 'Forbrydelse', id = 'K.K. 5001', months = 20, fine = 3500, color = 'grøn', description = 'Brugen af penge, tjenester og / eller ejendom for at vinde gunst hos en regeringstjenestemand'},
        [2] = {title = 'Anti-maskelov', class = 'Overtrædelse', id = 'K.K. 5002', months = 0, fine = 750, color = 'grøn', description = 'At bære maske i en forbudt zone'},
        [3] = {title = 'Besiddelse af Kontrabande i en Regeringsfacilitet', class = 'Forbrydelse', id = 'K.K. 5003', months = 25, fine = 1000, color = 'grøn', description = 'At være i besiddelse af genstande, der er ulovlige, mens man er inden for en regeringsbygning'},
        [4] = {title = 'Kriminel Besiddelse af Stjålet Ejendom', class = 'Forbrydelse', id = 'K.K. 5004', months = 10, fine = 500, color = 'grøn', description = 'At være i besiddelse af genstande, der er stjålet vidende eller ikke'},
        [5] = {title = 'Flugt', class = 'Forbrydelse', id = 'K.K. 5005', months = 10, fine = 450, color = 'grøn', description = 'Handlingen med vilje og vidende at forlade varetægt, mens man lovligt bliver anholdt, tilbageholdt eller i fængsel'},
        [6] = {title = 'Fængselsflugt', class = 'Forbrydelse', id = 'K.K. 5006', months = 30, fine = 2500, color = 'orange', description = 'Handlingen med at forlade statslig varetægt fra en stats- eller amtsfængselsfacilitet'},
        [7] = {title = 'Medskyldig til Fængselsflugt', class = 'Forbrydelse', id = 'K.K. 5007', months = 25, fine = 2000, color = 'orange', description = 'At være til stede og / eller deltage i handlingen af den primære anklage'},
        [8] = {title = 'Forsøgt Fængselsflugt', class = 'Forbrydelse', id = 'K.K. 5008', months = 20, fine = 1500, color = 'orange', description = 'Vilje og forsøg på at flygte fra en stats- eller amtsfængselsfacilitet'},
        [9] = {title = 'Mened', class = 'Forbrydelse', id = 'K.K. 5009', months = 0, fine = 0, color = 'grøn', description = 'Handlingen med at afgive falske oplysninger, mens man er juridisk forpligtet til at tale sandheden'},
        [10] = {title = 'Overtrædelse af et Tilhold', class = 'Forbrydelse', id = 'K.K. 5010', months = 20, fine = 2250, color = 'grøn', description = 'Vilfuld og vidende krænkelse af retligt påbudte beskyttelsesdokumenter'},
        [11] = {title = 'Økonomisk Kriminalitet', class = 'Forbrydelse', id = 'K.K. 5011', months = 45, fine = 10000, color = 'grøn', description = 'Vilfuld og vidende overførsel af midler fra ikke-personlige bankkonti til personlige bankkonti med henblik på personlig gevinst'},
        [12] = {title = 'Ullovlig Praksis', class = 'Forbrydelse', id = 'K.K. 5012', months = 15, fine = 1500, color = 'orange', description = 'Handlingen med at udføre en service uden korrekt juridisk licens og godkendelse'},
        [13] = {title = 'Misbrug af Nødsystemer', class = 'Overtrædelse', id = 'K.K. 5013', months = 0, fine = 600, color = 'orange', description = 'Brug af regeringens nødudstyr til et ikke-tilladt formål'},
        [14] = {title = 'Sammensværgelse', class = 'Forbrydelse', id = 'K.K. 5014', months = 10, fine = 450, color = 'grøn', description = 'Handlingen med at planlægge en forbrydelse, men endnu ikke begå forbrydelsen'},
        [15] = {title = 'Overtrædelse af en Retsafgørelse', class = 'Forbrydelse', id = 'K.K. 5015', months = 0, fine = 0, color = 'orange', description = 'Overtrædelse af domstolsbeslutninger dokumentation'},
        [16] = {title = 'Undladelse af at Møde', class = 'Forbrydelse', id = 'K.K. 5016', months = 0, fine = 0, color = 'orange', description = 'Når en person, der er juridisk forpligtet til at møde i retten, ikke gør det'},
        [17] = {title = 'Foragt for Domstolen', class = 'Forbrydelse', id = 'K.K. 5017', months = 0, fine = 0, color = 'orange', description = 'Forstyrrelse af retsmøder i en retssal, mens den er i session (retlig afgørelse)'},
        [18] = {title = 'Modstand mod Anholdelse', class = 'Overtrædelse', id = 'K.K. 5018', months = 5, fine = 300, color = 'orange', description = 'Handlingen med ikke at tillade fredsofficerer at tage dig i varetægt villigt'},
    },
    [6] = {
        [1] = {title = 'Overtrædelse af en Fredsofficer', class = 'Overtrædelse', id = 'K.K. 6001', months = 0, fine = 750, color = 'grøn', description = 'Vilfuld tilsidesættelse af en lovlig ordre'},
        [2] = {title = 'Uordentlig Opførsel', class = 'Overtrædelse', id = 'K.K. 6002', months = 0, fine = 250, color = 'grøn', description = 'At handle på en måde, der skaber en farlig eller fysisk fornærmende tilstand ved enhver handling, der tjener intet legitimt formål for aktøren.'},
        [3] = {title = 'Forstyrrelse af Freden', class = 'Overtrædelse', id = 'K.K. 6003', months = 0, fine = 350, color = 'grøn', description = 'Handling på en måde, der forårsager uro og forstyrrer den offentlige orden'},
        [4] = {title = 'Falsk Rapportering', class = 'Forbrydelse', id = 'K.K. 6004', months = 10, fine = 750, color = 'grøn', description = 'Handlingen med at rapportere en forbrydelse, der ikke fandt sted'},
        [5] = {title = 'Chikane', class = 'Forbrydelse', id = 'K.K. 6005', months = 10, fine = 500, color = 'orange', description = 'Den gentagne forstyrrelse eller verbale angreb på en anden person'},
        [6] = {title = 'Forseelse af Retsforhold', class = 'Forbrydelse', id = 'K.K. 6006', months = 10, fine = 500, color = 'grøn', description = 'Handling på en måde, der hindrer retfærdighedsprocessen eller lovlige undersøgelser'},
        [7] = {title = 'Forbrydelse af Retsforhold', class = 'Forbrydelse', id = 'K.K. 6007', months = 15, fine = 900, color = 'grøn', description = 'Handling på en måde, der hindrer retfærdighedsprocessen eller lovlige undersøgelser under anvendelse af vold'},
        [8] = {title = 'Oprørshandling', class = 'Forbrydelse', id = 'K.K. 6008', months = 25, fine = 1000, color = 'orange', description = 'Forårsager civil uro på en måde, der opfordrer en gruppe til at forvolde skade på mennesker eller ejendom'},
        [9] = {title = 'Hængende på Offentlige Ejendomme', class = 'Overtrædelse', id = 'K.K. 6009', months = 0, fine = 500, color = 'grøn', description = 'Når nogen er til stede på en offentlig ejendom i en udstrakt periode'},
        [10] = {title = 'Manipulation', class = 'Forbrydelse', id = 'K.K. 6010', months = 10, fine = 500, color = 'grøn', description = 'Når nogen vilfullydt, vidende og indirekte interfererer med nøglepunkter i en lovlig undersøgelse'},
        [11] = {title = 'Manipulation af Køretøj', class = 'Forbrydelse', id = 'K.K. 6011', months = 15, fine = 750, color = 'grøn', description = 'Vilfuld og vidende indblanding med køretøjets normale funktion'},
        [12] = {title = 'Manipulation af Beviser', class = 'Forbrydelse', id = 'K.K. 6012', months = 20, fine = 1000, color = 'grøn', description = 'Vilfuld og vidende indblanding med beviser fra en lovlig undersøgelse'},
        [13] = {title = 'Manipulation af Vidner', class = 'Forbrydelse', id = 'K.K. 6013', months = 0, fine = 0, color = 'grøn', description = 'Vilfuld og vidende træning eller tvang af en vidne i en lovlig undersøgelse'},
        [14] = {title = 'Undlader at give Identifikation', class = 'Forbrydelse', id = 'K.K. 6014', months = 15, fine = 1500, color = 'grøn', description = 'Handlingen med ikke at præsentere identifikation, når det er lovligt påkrævet'},
        [15] = {title = 'Selvtægt', class = 'Forbrydelse', id = 'K.K. 6015', months = 30, fine = 1500, color = 'orange', description = 'Handlingen med at deltage i håndhævelse af loven med juridisk myndighed til at gøre det'},
        [16] = {title = 'Ulovlig Forsamling', class = 'Forbrydelse', id = 'K.K. 6016', months = 10, fine = 750, color = 'orange', description = 'Når en stor gruppe samles på et sted, der kræver forudgående godkendelse for at gøre det'},
        [17] = {title = 'Regeringskorruption', class = 'Forbrydelse', id = 'K.K. 6017', months = 0, fine = 0, color = 'rød', description = 'Handlingen med at bruge politisk stilling og magt til egen vinding'},
        [18] = {title = 'Chikane', class = 'Forbrydelse', id = 'K.K. 6018', months = 40, fine = 1500, color = 'orange', description = 'Når én person overvåger en anden uden deres samtykke'},
        [19] = {title = 'Medvirken og Støtte', class = 'Forbrydelse', id = 'K.K. 6019', months = 15, fine = 450, color = 'orange', description = 'At hjælpe nogen med at begå eller opfordre nogen til at begå en forbrydelse'},
        [20] = {title = 'Skjule en Flygtning', class = 'Forbrydelse', id = 'K.K. 6020', months = 10, fine = 1000, color = 'grøn', description = 'Når nogen vilje skjuler en anden, der er eftersøgt af myndighederne'},
    },
    [7] = {
        [1] = {title = 'Forbrydelse af Besiddelse af Marihuana', class = 'Forbrydelse', id = 'K.K. 7001', months = 5, fine = 250, color = 'grøn', description = 'Besiddelse af en mængde marihuana på mindre end 4 blunts'},
        [2] = {title = 'Forbrydelse af Fremstilling af Marihuana', class = 'Forbrydelse', id = 'K.K. 7002', months = 15, fine = 1000, color = 'rød', description = 'Besiddelse af en mængde marihuana fra fremstilling'},
        [3] = {title = 'Dyrkning af Marihuana A', class = 'Forbrydelse', id = 'K.K. 7003', months = 10, fine = 750, color = 'grøn', description = 'Besiddelse af 4 eller færre marihuana-planter'},
        [4] = {title = 'Dyrkning af Marihuana B', class = 'Forbrydelse', id = 'K.K. 7004', months = 30, fine = 1500, color = 'orange', description = 'Besiddelse af 5 eller flere marihuana-planter'},
        [5] = {title = 'Besiddelse af Marihuana med Henblik på Distribution', class = 'Forbrydelse', id = 'K.K. 7005', months = 30, fine = 3000, color = 'orange', description = 'Besiddelse af en mængde marihuana med henblik på distribution'},
        [6] = {title = 'Forbrydelse af Besiddelse af Kokain', class = 'Forbrydelse', id = 'K.K. 7006', months = 7, fine = 500, color = 'grøn', description = 'Besiddelse af kokain i en lille mængde normalt til personlig brug'},
        [7] = {title = 'Forbrydelse af Fremstilling af Besiddelse af Kokain', class = 'Forbrydelse', id = 'K.K. 7007', months = 25, fine = 1500, color = 'rød', description = 'Besiddelse af en mængde kokain fra fremstilling'},
        [8] = {title = 'Besiddelse af Kokain med Henblik på Distribution', class = 'Forbrydelse', id = 'K.K. 7008', months = 35, fine = 4500, color = 'orange', description = 'Besiddelse af en mængde kokain med henblik på distribution'},
        [9] = {title = 'Forbrydelse af Besiddelse af Methamfetamin', class = 'Forbrydelse', id = 'K.K. 7009', months = 7, fine = 500, color = 'grøn', description = 'Besiddelse af methamfetamin i en lille mængde normalt til personlig brug'},
        [10] = {title = 'Forbrydelse af Fremstilling af Besiddelse af Methamfetamin', class = 'Forbrydelse', id = 'K.K. 7010', months = 25, fine = 1500, color = 'rød', description = 'Besiddelse af en mængde methamfetamin fra fremstilling'},
        [11] = {title = 'Besiddelse af Methamfetamin med Henblik på Distribution', class = 'Forbrydelse', id = 'K.K. 7011', months = 35, fine = 4500, color = 'orange', description = 'Besiddelse af en mængde methamfetamin med henblik på distribution'},
        [12] = {title = 'Forbrydelse af Besiddelse af Oxy / Vicodin', class = 'Forbrydelse', id = 'K.K. 7012', months = 7, fine = 500, color = 'grøn', description = 'Besiddelse af oxy / vicodin i en lille mængde normalt til personlig brug uden recept'},
        [13] = {title = 'Forbrydelse af Fremstilling af Besiddelse af Oxy / Vicodin', class = 'Forbrydelse', id = 'K.K. 7013', months = 25, fine = 1500, color = 'rød', description = 'Besiddelse af en mængde oxy / vicodin fra fremstilling'},
        [14] = {title = 'Forbrydelse af Besiddelse af Oxy / Vicodin med Henblik på Distribution', class = 'Forbrydelse', id = 'K.K. 7014', months = 35, fine = 4500, color = 'orange', description = 'Besiddelse af en mængde oxy / vicodin med henblik på distribution'},
        [15] = {title = 'Forbrydelse af Besiddelse af Ecstasy', class = 'Forbrydelse', id = 'K.K. 7015', months = 7, fine = 500, color = 'grøn', description = 'Besiddelse af ecstasy i en lille mængde normalt til personlig brug'},
        [16] = {title = 'Forbrydelse af Fremstilling af Besiddelse af Ecstasy', class = 'Forbrydelse', id = 'K.K. 7016', months = 25, fine = 1500, color = 'rød', description = 'Besiddelse af en mængde ecstasy fra fremstilling'},
        [17] = {title = 'Besiddelse af Ecstasy med Henblik på Distribution', class = 'Forbrydelse', id = 'K.K. 7017', months = 35, fine = 4500, color = 'orange', description = 'Besiddelse af en mængde ecstasy med henblik på distribution'},
        [18] = {title = 'Forbrydelse af Besiddelse af Opium', class = 'Forbrydelse', id = 'K.K. 7018', months = 7, fine = 500, color = 'grøn', description = 'Besiddelse af opium i en lille mængde normalt til personlig brug'},
        [19] = {title = 'Forbrydelse af Fremstilling af Besiddelse af Opium', class = 'Forbrydelse', id = 'K.K. 7019', months = 25, fine = 1500, color = 'rød', description = 'Besiddelse af en mængde opium fra fremstilling'},
        [20] = {title = 'Besiddelse af Opium med Henblik på Distribution', class = 'Forbrydelse', id = 'K.K. 7020', months = 35, fine = 4500, color = 'orange', description = 'Besiddelse af en mængde opium med henblik på distribution'},
        [21] = {title = 'Forbrydelse af Besiddelse af Adderall', class = 'Forbrydelse', id = 'K.K. 7021', months = 7, fine = 500, color = 'grøn', description = 'Besiddelse af adderall i en lille mængde normalt til personlig brug uden recept'},
        [22] = {title = 'Forbrydelse af Fremstilling af Besiddelse af Adderall', class = 'Forbrydelse', id = 'K.K. 7022', months = 25, fine = 1500, color = 'rød', description = 'Besiddelse af en mængde adderall fra fremstilling'},
        [23] = {title = 'Besiddelse af Adderall med Henblik på Distribution', class = 'Forbrydelse', id = 'K.K. 7023', months = 35, fine = 4500, color = 'orange', description = 'Besiddelse af en mængde adderall med henblik på distribution'},
        [24] = {title = 'Forbrydelse af Besiddelse af Xanax', class = 'Forbrydelse', id = 'K.K. 7024', months = 7, fine = 500, color = 'grøn', description = 'Besiddelse af xanax i en lille mængde normalt til personlig brug uden recept'},
        [25] = {title = 'Forbrydelse af Fremstilling af Besiddelse af Xanax', class = 'Forbrydelse', id = 'K.K. 7025', months = 25, fine = 1500, color = 'rød', description = 'Besiddelse af en mængde xanax fra fremstilling'},
        [26] = {title = 'Besiddelse af Xanax med Henblik på Distribution', class = 'Forbrydelse', id = 'K.K. 7026', months = 35, fine = 4500, color = 'orange', description = 'Besiddelse af en mængde xanax med henblik på distribution'},
        [27] = {title = 'Forbrydelse af Besiddelse af Shrooms', class = 'Forbrydelse', id = 'K.K. 7027', months = 7, fine = 500, color = 'grøn', description = 'Besiddelse af shrooms i en lille mængde normalt til personlig brug'},
        [28] = {title = 'Forbrydelse af Fremstilling af Besiddelse af Shrooms', class = 'Forbrydelse', id = 'K.K. 7028', months = 25, fine = 1500, color = 'rød', description = 'Besiddelse af en mængde shrooms fra fremstilling'},
        [29] = {title = 'Besiddelse af Shrooms med Henblik på Distribution', class = 'Forbrydelse', id = 'K.K. 7029', months = 35, fine = 4500, color = 'orange', description = 'Besiddelse af en mængde shrooms med henblik på distribution'},
        [30] = {title = 'Forbrydelse af Besiddelse af Lean', class = 'Forbrydelse', id = 'K.K. 7030', months = 7, fine = 500, color = 'grøn', description = 'Besiddelse af lean i en lille mængde normalt til personlig brug'},
        [31] = {title = 'Forbrydelse af Fremstilling af Besiddelse af Lean', class = 'Forbrydelse', id = 'K.K. 7031', months = 25, fine = 1500, color = 'rød', description = 'Besiddelse af en mængde lean fra fremstilling'},
        [32] = {title = 'Besiddelse af Lean med Henblik på Distribution', class = 'Forbrydelse', id = 'K.K. 7032', months = 35, fine = 4500, color = 'orange', description = 'Besiddelse af en mængde lean med henblik på distribution'},
        [33] = {title = 'Salg af et kontrolleret stof', class = 'Forbrydelse', id = 'K.K. 7033', months = 10, fine = 1000, color = 'grøn', description = 'Salg af et stof, der er kontrolleret ved lov'},
        [34] = {title = 'Narkotikahandel', class = 'Forbrydelse', id = 'K.K. 7034', months = 0, fine = 0, color = 'rød', description = 'Den storskala bevægelse af ulovlige stoffer'},
        [35] = {title = 'Vanhelligelse af et menneskeligt lig', class = 'Forbrydelse', id = 'K.K. 7035', months = 20, fine = 1500, color = 'orange', description = 'Når nogen skader, forstyrrer eller ødelægger resterne af en anden person'},
        [36] = {title = 'Offentlig beruselse', class = 'Forseelse', id = 'K.K. 7036', months = 0, fine = 500, color = 'grøn', description = 'Når nogen er beruset over den lovlige grænse i offentligheden'},
        [37] = {title = 'Offentlig uanstændighed', class = 'Forbrydelse', id = 'K.K. 7037', months = 10, fine = 750, color = 'grøn', description = 'Handlingen af nogen, der udsætter sig selv på en måde, der krænker offentlig moral'},
    },
    [8] = {
        [1] = {title = 'Kriminel Besiddelse af Våben Klasse A', class = 'Forbrydelse', id = 'K.K. 8001', months = 10, fine = 500, color = 'grøn', description = 'Besiddelse af en klasse A-firearm uden licens'},
        [2] = {title = 'Kriminel Besiddelse af Våben Klasse B', class = 'Forbrydelse', id = 'K.K. 8002', months = 15, fine = 1000, color = 'grøn', description = 'Besiddelse af en klasse B-firearm uden licens'},
        [3] = {title = 'Kriminel Besiddelse af Våben Klasse C', class = 'Forbrydelse', id = 'K.K. 8003', months = 30, fine = 3500, color = 'grøn', description = 'Besiddelse af en klasse C-firearm uden licens'},
        [4] = {title = 'Kriminel Besiddelse af Våben Klasse D', class = 'Forbrydelse', id = 'K.K. 8004', months = 25, fine = 1500, color = 'grøn', description = 'Besiddelse af en klasse D-firearm uden licens'},
        [5] = {title = 'Kriminel Salg af Våben Klasse A', class = 'Forbrydelse', id = 'K.K. 8005', months = 15, fine = 1000, color = 'orange', description = 'Handlingen med at sælge en klasse A-firearm uden licens'},
        [6] = {title = 'Kriminel Salg af Våben Klasse B', class = 'Forbrydelse', id = 'K.K. 8006', months = 20, fine = 2000, color = 'orange', description = 'Handlingen med at sælge en klasse B-firearm uden licens'},
        [7] = {title = 'Kriminel Salg af Våben Klasse C', class = 'Forbrydelse', id = 'K.K. 8007', months = 35, fine = 7000, color = 'orange', description = 'Handlingen med at sælge en klasse C-firearm uden licens'},
        [8] = {title = 'Kriminel Salg af Våben Klasse D', class = 'Forbrydelse', id = 'K.K. 8008', months = 30, fine = 3000, color = 'orange', description = 'Handlingen med at sælge en klasse D-firearm uden licens'},
        [9] = {title = 'Kriminel Brug af Våben', class = 'Forseelse', id = 'K.K. 8009', months = 10, fine = 450, color = 'orange', description = 'Brug af et våben under begåelse af en forbrydelse'},
        [10] = {title = 'Besiddelse af Ulige Skydevåben Modifikationer', class = 'Forseelse', id = 'K.K. 8010', months = 10, fine = 300, color = 'grøn', description = 'At være i besiddelse af ulovlige skydevåbenmodifikationer'},
        [11] = {title = 'Våbenhandel', class = 'Forbrydelse', id = 'K.K. 8011', months = 0, fine = 0, color = 'rød', description = 'Transport af en stor mængde våben fra et sted til et andet'},
        [12] = {title = 'Viften med et Våben', class = 'Forseelse', id = 'K.K. 8012', months = 15, fine = 500, color = 'orange', description = 'Handlingen med at gøre en ildvåben bevidst synlig'},
        [13] = {title = 'Oprør', class = 'Forbrydelse', id = 'K.K. 8013', months = 0, fine = 0, color = 'rød', description = 'Forsøg på at vælte regeringen med vold'},
        [14] = {title = 'Flyvning ind i begrænset luftrum', class = 'Forbrydelse', id = 'K.K. 8014', months = 20, fine = 1500, color = 'grøn', description = 'Pilotering af et fly ind i luftrum, der er kontrolleret af regeringen'},
        [15] = {title = 'Jaywalking', class = 'Forseelse', id = 'K.K. 8015', months = 0, fine = 150, color = 'grøn', description = 'At krydse en vej på en måde, der er farlig for motorkøretøjer'},
        [16] = {title = 'Kriminel Brug af Eksplosiver', class = 'Forbrydelse', id = 'K.K. 8016', months = 30, fine = 2500, color = 'orange', description = 'Brug af eksplosiver til begåelse af en forbrydelse'},
    },
    [9] = {
        [1] = {title = 'Kørsel under påvirkning', class = 'Forseelse', id = 'K.K. 9001', months = 5, fine = 300, color = 'grøn', description = 'Betjening af et motorkøretøj under påvirkning af alkohol'},
        [2] = {title = 'Undvigende', class = 'Forseelse', id = 'K.K. 9002', months = 5, fine = 400, color = 'grøn', description = 'Skjuler sig eller løber væk fra lovlig tilbageholdelse'},
        [3] = {title = 'Rådighedsløs Undvigelse', class = 'Forbrydelse', id = 'K.K. 9003', months = 10, fine = 800, color = 'orange', description = 'At hensynsløst ignorere sikkerhed og skjule sig eller løbe væk fra lovlig tilbageholdelse'},
        [4] = {title = 'Undlader at give efter for udrykningskøretøj', class = 'Forseelse', id = 'K.K. 9004', months = 0, fine = 600, color = 'grøn', description = 'Giver ikke plads til udrykningskøretøjer'},
        [5] = {title = 'Overtrædelse af færdselsregler', class = 'Forseelse', id = 'K.K. 9005', months = 0, fine = 150, color = 'grøn', description = 'Følger ikke vejens sikkerhedsanordninger'},
        [6] = {title = 'Ikke-funktionel køretøj', class = 'Forseelse', id = 'K.K. 9006', months = 0, fine = 75, color = 'grøn', description = 'Har et køretøj, der ikke længere er funktionelt på vejen'},
        [7] = {title = 'Førløs Kørsel', class = 'Forseelse', id = 'K.K. 9007', months = 0, fine = 300, color = 'grøn', description = 'Kører på en måde, der uvidende ignorerer sikkerheden'},
        [8] = {title = 'Rådighedsløs Kørsel', class = 'Forseelse', id = 'K.K. 9008', months = 10, fine = 750, color = 'orange', description = 'Kører på en måde, der bevidst ignorerer sikkerheden'},
        [9] = {title = 'Tredje Grad Hastighedsoverskridelse', class = 'Forseelse', id = 'K.K. 9009', months = 0, fine = 225, color = 'grøn', description = 'Hastighedsoverskridelse med 15 over grænsen'},
        [10] = {title = 'Anden Grad Hastighedsoverskridelse', class = 'Forseelse', id = 'K.K. 9010', months = 0, fine = 450, color = 'grøn', description = 'Hastighedsoverskridelse med 35 over grænsen'},
        [11] = {title = 'Første Grad Hastighedsoverskridelse', class = 'Forseelse', id = 'K.K. 9011', months = 0, fine = 750, color = 'grøn', description = 'Hastighedsoverskridelse med 50 over grænsen'},
        [12] = {title = 'Kørsel uden gyldig kørekort', class = 'Forseelse', id = 'K.K. 9012', months = 0, fine = 500, color = 'grøn', description = 'Betjening af et motorkøretøj uden gyldig licens'},
        [13] = {title = 'Ulovlig U-sving', class = 'Forseelse', id = 'K.K. 9013', months = 0, fine = 75, color = 'grøn', description = 'Udfører et U-sving, hvor det er forbudt'},
        [14] = {title = 'Ulovlig Overhaling', class = 'Forseelse', id = 'K.K. 9014', months = 0, fine = 300, color = 'grøn', description = 'Overhaler andre motorkøretøjer på en forbudt måde'},
        [15] = {title = 'Undladelse af at holde vejbanen', class = 'Forseelse', id = 'K.K. 9015', months = 0, fine = 300, color = 'grøn', description = 'Bliver ikke i den korrekte vejbane med et motorkøretøj'},
        [16] = {title = 'Ulovlig Vendning', class = 'Forseelse', id = 'K.K. 9016', months = 0, fine = 150, color = 'grøn', description = 'Udfører en vending, hvor det er forbudt'},
        [17] = {title = 'Undlader at stoppe', class = 'Forseelse', id = 'K.K. 9017', months = 0, fine = 600, color = 'grøn', description = 'Stopper ikke for en lovlig stop eller trafikanordning'},
        [18] = {title = 'Uautoriseret parkering', class = 'Forseelse', id = 'K.K. 9018', months = 0, fine = 300, color = 'grøn', description = 'Parkerer et køretøj på et sted, der kræver godkendelse med nogen'},
        [19] = {title = 'Påkørsel og Flugt', class = 'Forseelse', id = 'K.K. 9019', months = 10, fine = 500, color = 'grøn', description = 'Rammer en anden person eller et køretøj og flygter fra stedet'},
        [20] = {title = 'Kørsel uden forlygter eller signaler', class = 'Forseelse', id = 'K.K. 9020', months = 0, fine = 300, color = 'grøn', description = 'Betjening af et køretøj uden funktionelle lys'},
        [21] = {title = 'Gaderæs', class = 'Forbrydelse', id = 'K.K. 9021', months = 15, fine = 1500, color = 'grøn', description = 'Betjening af motorkøretøjer i en konkurrence'},
        [22] = {title = 'Pilotering uden korrekt licens', class = 'Forbrydelse', id = 'K.K. 9022', months = 20, fine = 1500, color = 'orange', description = 'Mangler gyldig licens ved betjening af et fly'},
        [23] = {title = 'Ulødig brug af et motorkøretøj', class = 'Forseelse', id = 'K.K. 9023', months = 10, fine = 750, color = 'grøn', description = 'Brugen af et motorkøretøj uden en lovlig grund'},
    },
    [10] = {
        [1] = {title = 'Jagt i begrænsede områder', class = 'Forseelse', id = 'K.K. 10001', months = 0, fine = 450, color = 'grøn', description = 'At høste vildt i områder, hvor det er forbudt'},
        [2] = {title = 'Ulovlig jagt', class = 'Forseelse', id = 'K.K. 10002', months = 0, fine = 450, color = 'grøn', description = 'At høste vildt uden korrekt licens'},
        [3] = {title = 'Dyremishandling', class = 'Forseelse', id = 'K.K. 10003', months = 10, fine = 450, color = 'grøn', description = 'Handlingen med at mishandle et dyr, vidende eller ej'},
        [4] = {title = 'Jagt med et ikke-jagtvåben', class = 'Forseelse', id = 'K.K. 10004', months = 10, fine = 750, color = 'grøn', description = 'At bruge et våben, der ikke lovligt er angivet eller fremstillet til at blive brugt til at høste vildt'},
        [5] = {title = 'Jagt uden for jagttimerne', class = 'Forseelse', id = 'K.K. 10005', months = 0, fine = 750, color = 'grøn', description = 'At høste dyr uden for de angivne tidspunkter'},
        [6] = {title = 'Overjagt', class = 'Forseelse', id = 'K.K. 10006', months = 10, fine = 1000, color = 'grøn', description = 'At tage mere end lovligt specificeret mængde vildt'},
        [7] = {title = 'Krybskytteri', class = 'Forbrydelse', id = 'K.K. 10007', months = 20, fine = 1250, color = 'rød', description = 'At høste et dyr, der er angivet som lovligt ikke-høstbart'},
    }
}

Config.AllowedJobs = {}
for index, value in pairs(Config.PoliceJobs) do
    Config.AllowedJobs[index] = value
end
for index, value in pairs(Config.AmbulanceJobs) do
    Config.AllowedJobs[index] = value
end
for index, value in pairs(Config.DojJobs) do
    Config.AllowedJobs[index] = value
end

Config.ColorNames = {
    [0] = "metallic sort",
    [1] = "metallic grafit sort",
    [2] = "metallic sort stål",
    [3] = "metallic mørk sølv",
    [4] = "metallic sølv",
    [5] = "metallic blå sølv",
    [6] = "metallic stålgrå",
    [7] = "metallic skygge sølv",
    [8] = "metallic sten sølv",
    [9] = "metallic midnatsølv",
    [10] = "metallic gun metal",
    [11] = "metallic antracit grå",
    [12] = "mat sort",
    [13] = "mat grå",
    [14] = "mat lysegrå",
    [15] = "util sort",
    [16] = "util sort poly",
    [17] = "util mørk sølv",
    [18] = "util sølv",
    [19] = "util gun metal",
    [20] = "util skygge sølv",
    [21] = "slidt sort",
    [22] = "slidt grafit",
    [23] = "slidt sølvgrå",
    [24] = "slidt sølv",
    [25] = "slidt blå sølv",
    [26] = "slidt skygge sølv",
    [27] = "metallic rød",
    [28] = "metallic torino rød",
    [29] = "metallic formel rød",
    [30] = "metallic blaze rød",
    [31] = "metallic yndefuld rød",
    [32] = "metallic granatrød",
    [33] = "metallic ørkenrød",
    [34] = "metallic cabernet rød",
    [35] = "metallic slik rød",
    [36] = "metallic solopgang orange",
    [37] = "metallic klassisk guld",
    [38] = "metallic orange",
    [39] = "mat rød",
    [40] = "mat mørk rød",
    [41] = "mat orange",
    [42] = "mat gul",
    [43] = "util rød",
    [44] = "util lyse rød",
    [45] = "util granatrød",
    [46] = "slidt rød",
    [47] = "slidt gylden rød",
    [48] = "slidt mørk rød",
    [49] = "metallic mørkegrøn",
    [50] = "metallic racing grøn",
    [51] = "metallic havgrøn",
    [52] = "metallic olivengrøn",
    [53] = "metallic grøn",
    [54] = "metallic benzinblå grøn",
    [55] = "mat limegrøn",
    [56] = "util mørkegrøn",
    [57] = "util grøn",
    [58] = "slidt mørkegrøn",
    [59] = "slidt grøn",
    [60] = "slidt seawash",
    [61] = "metallic midnatsblå",
    [62] = "metallic mørk blå",
    [63] = "metallic saxonyblå",
    [64] = "metallic blå",
    [65] = "metallic mariner blå",
    [66] = "metallic havnblå",
    [67] = "metallic diamantblå",
    [68] = "metallic surfblå",
    [69] = "metallic søblå",
    [70] = "metallic lyst blå",
    [71] = "metallic lilla blå",
    [72] = "metallic spinnakerblå",
    [73] = "metallic ultra blå",
    [74] = "metallic lyst blå",
    [75] = "util mørkeblå",
    [76] = "util midnatsblå",
    [77] = "util blå",
    [78] = "util havskum blå",
    [79] = "uil lynblå",
    [80] = "util maui blå poly",
    [81] = "util lyst blå",
    [82] = "mat mørkeblå",
    [83] = "mat blå",
    [84] = "mat midnatsblå",
    [85] = "slidt mørkeblå",
    [86] = "slidt blå",
    [87] = "slidt lys blå",
    [88] = "metallic taxa gul",
    [89] = "metallic race gul",
    [90] = "metallic bronze",
    [91] = "metallic gul fugl",
    [92] = "metallic lime",
    [93] = "metallic champagne",
    [94] = "metallic pueblo beige",
    [95] = "metallic mørk elfenben",
    [96] = "metallic choko brun",
    [97] = "metallic gylden brun",
    [98] = "metallic lysebrun",
    [99] = "metallic halm beige",
    [100] = "metallic mosbrun",
    [101] = "metallic biston brun",
    [102] = "metallic bøgetræ",
    [103] = "metallic mørk bøgetræ",
    [104] = "metallic choko appelsin",
    [105] = "metallic strand sand",
    [106] = "metallic sol blegnet sand",
    [107] = "metallic fløde",
    [108] = "util brun",
    [109] = "util medium brun",
    [110] = "util lys brun",
    [111] = "metallic hvid",
    [112] = "metallic frost hvid",
    [113] = "slidt honning beige",
    [114] = "slidt brun",
    [115] = "slidt mørk brun",
    [116] = "slidt halm beige",
    [117] = "børstet stål",
    [118] = "børstet sort stål",
    [119] = "børstet aluminium",
    [120] = "krom",
    [121] = "slidt off white",
    [122] = "util off white",
    [123] = "slidt orange",
    [124] = "slidt lys orange",
    [125] = "metallic securicor grøn",
    [126] = "slidt taxa gul",
    [127] = "politi bil blå",
    [128] = "mat grøn",
    [129] = "mat brun",
    [130] = "slidt orange",
    [131] = "mat hvid",
    [132] = "slidt hvid",
    [133] = "slidt oliven army grøn",
    [134] = "ren hvid",
    [135] = "varm pink",
    [136] = "laksrosa",
    [137] = "metallic vermillion pink",
    [138] = "orange",
    [139] = "grøn",
    [140] = "blå",
    [141] = "metallic sort blå",
    [142] = "metallic sort lilla",
    [143] = "metallic sort rød",
    [144] = "jæger grøn",
    [145] = "metallic lilla",
    [146] = "metallic v mørkeblå",
    [147] = "modshop sort1",
    [148] = "mat lilla",
    [149] = "mat mørk lilla",
    [150] = "metallic lava rød",
    [151] = "mat skov grøn",
    [152] = "mat oliven drab",
    [153] = "mat ørken brun",
    [154] = "mat ørken tan",
    [155] = "mat folie grøn",
    [156] = "standard legeringsfarve",
    [157] = "epsilon blå",
    [158] = "ukendt",
}

Config.ColorInformation = {
    [0] = "sort",
    [1] = "sort",
    [2] = "sort",
    [3] = "mørk sølv",
    [4] = "sølv",
    [5] = "blå sølv",
    [6] = "sølv",
    [7] = "mørk sølv",
    [8] = "sølv",
    [9] = "blå sølv",
    [10] = "mørk sølv",
    [11] = "mørk sølv",
    [12] = "mat sort",
    [13] = "grå",
    [14] = "lys grå",
    [15] = "sort",
    [16] = "sort",
    [17] = "mørk sølv",
    [18] = "sølv",
    [19] = "util gunmetal",
    [20] = "sølv",
    [21] = "sort",
    [22] = "sort",
    [23] = "mørk sølv",
    [24] = "sølv",
    [25] = "blå sølv",
    [26] = "mørk sølv",
    [27] = "rød",
    [28] = "torino rød",
    [29] = "formel rød",
    [30] = "blaze rød",
    [31] = "graceful rød",
    [32] = "garnet rød",
    [33] = "ørken rød",
    [34] = "cabernet rød",
    [35] = "candy rød",
    [36] = "orange",
    [37] = "guld",
    [38] = "orange",
    [39] = "rød",
    [40] = "mat mørk rød",
    [41] = "orange",
    [42] = "mat gul",
    [43] = "rød",
    [44] = "bright rød",
    [45] = "garnet rød",
    [46] = "rød",
    [47] = "rød",
    [48] = "mørk rød",
    [49] = "mørkegrøn",
    [50] = "racergrøn",
    [51] = "søgrøn",
    [52] = "oliven grøn",
    [53] = "grøn",
    [54] = "benzinblågrøn",
    [55] = "mat limegrøn",
    [56] = "mørkegrøn",
    [57] = "grøn",
    [58] = "mørkegrøn",
    [59] = "grøn",
    [60] = "søvask",
    [61] = "midnat blå",
    [62] = "mørkeblå",
    [63] = "saksblå",
    [64] = "blå",
    [65] = "blå",
    [66] = "blå",
    [67] = "diamantblå",
    [68] = "blå",
    [69] = "blå",
    [70] = "bright blå",
    [71] = "lilla blå",
    [72] = "blå",
    [73] = "ultrablå",
    [74] = "bright blå",
    [75] = "mørkeblå",
    [76] = "midnat blå",
    [77] = "blå",
    [78] = "blå",
    [79] = "lynnblå",
    [80] = "blå",
    [81] = "bright blå",
    [82] = "mat mørkeblå",
    [83] = "mat blå",
    [84] = "mat blå",
    [85] = "mørkeblå",
    [86] = "blå",
    [87] = "lynnblå",
    [88] = "gul",
    [89] = "gul",
    [90] = "bronze",
    [91] = "gul",
    [92] = "lime",
    [93] = "champagne",
    [94] = "beige",
    [95] = "mørk elfenben",
    [96] = "brun",
    [97] = "brun",
    [98] = "lys brun",
    [99] = "beige",
    [100] = "brun",
    [101] = "brun",
    [102] = "bøg",
    [103] = "bøg",
    [104] = "chokoladeappelsin",
    [105] = "gul",
    [106] = "gul",
    [107] = "fløde",
    [108] = "brun",
    [109] = "brun",
    [110] = "brun",
    [111] = "hvid",
    [112] = "hvid",
    [113] = "beige",
    [114] = "brun",
    [115] = "brun",
    [116] = "beige",
    [117] = "stål",
    [118] = "sort stål",
    [119] = "aluminium",
    [120] = "krom",
    [121] = "slidt hvid",
    [122] = "off-white",
    [123] = "orange",
    [124] = "lys orange",
    [125] = "grøn",
    [126] = "gul",
    [127] = "blå",
    [128] = "grøn",
    [129] = "brun",
    [130] = "orange",
    [131] = "hvid",
    [132] = "hvid",
    [133] = "mørkegrøn",
    [134] = "hvid",
    [135] = "pink",
    [136] = "pink",
    [137] = "pink",
    [138] = "orange",
    [139] = "grøn",
    [140] = "blå",
    [141] = "sortblå",
    [142] = "sortlilla",
    [143] = "sortrød",
    [144] = "mørkegrøn",
    [145] = "lilla",
    [146] = "mørkeblå",
    [147] = "sort",
    [148] = "lilla",
    [149] = "mørkelilla",
    [150] = "rød",
    [151] = "mørkegrøn",
    [152] = "olivengrøn",
    [153] = "brun",
    [154] = "tan",
    [155] = "grøn",
    [156] = "sølv",
    [157] = "blå",
    [158] = "sort",
}

Config.ClassList = {
    [0] = "Kompakt",
    [1] = "Sedan",
    [2] = "SUV",
    [3] = "Coupe",
    [4] = "Muscle",
    [5] = "Sport Classic",
    [6] = "Sport",
    [7] = "Super",
    [8] = "Motorcykel",
    [9] = "Off-Road",
    [10] = "Industriel",
    [11] = "Værktøj",
    [12] = "Van",
    [13] = "Cykel",
    [14] = "Båd",
    [15] = "Helikopter",
    [16] = "Fly",
    [17] = "Service",
    [18] = "Nød",
    [19] = "Militær",
    [20] = "Erhverv",
    [21] = "Tog"
}

function GetJobType(job)
	if Config.PoliceJobs[job] then
		return 'police'
	elseif Config.AmbulanceJobs[job] then
		return 'ambulance'
	elseif Config.DojJobs[job] then
		return 'doj'
	else
		return nil
	end
end
